FROM ichylinux/hybitz-centos:7.9.2009

RUN sudo yum -y install sqlite-devel

ADD Gemfile Gemfile.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN yarn install && yarn cache clean

ADD  . ./
RUN sudo chown -R ${USER}:${USER} ./
