FROM hybitz-centos-7.7:latest

RUN sudo yum -y install sqlite-devel

ADD Gemfile Gemfile.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN yarn install

ADD  . ./
RUN sudo chown -R ${USER}:${USER} ./
